describe('Sign in with different methods', function() {
  beforeEach('navigate to home page', function() {
    cy.visit('/login')
    cy.get('.se-pre-con:hidden').as('loader')
    cy.get('@loader')
    cy.contains("Food&Drink")
    cy.url().should('include', '.com/login')
  })
  it('login happy path', function() {
    cy.get('[href="/login"]').click()
    cy.get('.se-pre-con').should('not.be.visible')
    cy.url().should('include', '.com/login')
    cy.get('#email')
      .type('cypress123@automation.com')
      .should('have.value', 'cypress123@automation.com')
    cy.get('#password')
      .type('AdamKowalski123!')
      .should('have.value', 'AdamKowalski123!')
    cy.get('.btn')
      .should('have.value', 'Zaloguj')
      .click()
      cy.get('.se-pre-con').should('not.be.visible')
    cy.url().should('include', '.com/dashboard')
    cy.get('[href="/edit_form"').should('be.visible')
  })
  it('login happy path', function() {
    cy.get('[href="/login"]').click()
    cy.get('.se-pre-con').should('not.be.visible')
    cy.url().should('include', '.com/login')
    cy.get('#email')
      .type('cypress123@automation.com')
      .should('have.value', 'cypress123@automation.com')
    cy.get('#password')
      .type('AdamKowalski123!')
      .should('have.value', 'AdamKowalski123!')
    cy.get('.btn')
      .should('have.value', 'Zaloguj')
      .click()
      cy.get('.se-pre-con').should('not.be.visible')
    cy.url().should('include', '.com/dashboard')
    cy.get('[href="/edit_form"').should('be.visible')
  })
})
